# Generated by Django 4.2.3 on 2023-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default='Valor por defecto', max_length=150),
        ),
    ]
