# Generated by Django 4.2.1 on 2023-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_post_cuerpo2_post_fechacreado_post_imagen1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtituloGenral',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtituloGenral2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
