# Generated by Django 4.2.1 on 2023-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_post_subtitulogenral_post_subtitulogenral2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtituloGenral',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtituloGenral2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
