# Generated by Django 4.2.1 on 2023-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_alter_post_subtitulogenral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pieDeFoto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
