# Generated by Django 4.2.1 on 2023-07-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_post_piedefoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pieDePosteo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cuerpo2',
            field=models.TextField(null=True),
        ),
    ]
