# Generated by Django 4.2.3 on 2023-07-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_comentario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='nombre',
        ),
    ]
