# Generated by Django 4.2.3 on 2023-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_remove_comentario_email_remove_comentario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='me_gusta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
