# Generated by Django 4.2.1 on 2023-07-27 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0011_megustacomentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='no_megusta',
            field=models.ManyToManyField(blank=True, related_name='comentario_no_Megusta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='me_gusta',
        ),
        migrations.AddField(
            model_name='comentario',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='comentario_Megusta', to=settings.AUTH_USER_MODEL),
        ),
    ]
