# Generated by Django 4.2.1 on 2023-07-27 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0012_remove_comentario_usuario_comentario_no_megusta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
