# Generated by Django 4.2.1 on 2023-08-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_facebook_alter_usuario_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('miembro', 'Miembro'), ('colaborador', 'Colaborador')], default='visitante', max_length=12),
        ),
    ]
